cloud:
  aws:
    credentials :
      accessKey : ${s3.accessKey}
      secretKey : ${s3.secretKey}
    s3:
      bucket: hanwul
    region:
      static : ap-northeast-2
    stack:
      auto: false
#    credentials:
#      instanceProfile: true